// import "./js/lesson-1/task1.js"
// import "./js/lesson-1/task2.js"
// import "./js/lesson-1/task3.js"
// import "./js/lesson-2/task-1.js"
// import "./js/lesson-2/task-1.js"
// import "./js/lesson-4/task.js"
// import "./js/lesson-4/blended-21-11-21.js"
// import "./js/lesson-4/24-11-20-group-Exersices.js"
import "./js/lesson-4/task-OOP-my-version-updated.js"
